apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: concurrent-redis
spec:
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    name: concurrent-redis
  type: ClusterIP
