apiVersion: v1
kind: Service
metadata:
  name: mediaserver
  labels:
    name: mediaserver
spec:
  ports:
  - port: 8000
    targetPort: web
    protocol: TCP
  selector:
    name: mediaserver
  type: ClusterIP
