apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: concurrent-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concurrent-redis
  template:
    metadata:
      labels:
        name: concurrent-redis
    spec:
      containers:
      - name: redis
        image: redis:7-bookworm
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
