apiVersion: v1
kind: Service
metadata:
  name: ccactivitypub
  labels:
    name: ccactivitypub
spec:
  ports:
  - port: 8000
    targetPort: web
    protocol: TCP
  selector:
    name: ccactivitypub
  type: ClusterIP
