!yisp &deploy
- lambda
- [props]
- !quote
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hyperproxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: hyperproxy
    template:
      metadata:
        labels:
          name: hyperproxy
      spec:
        containers:
          - name: hyperproxy
            image: *props.image
            ports:
              - name: web
                containerPort: 8000
            env:
              - name: PORT
                value: "8000"
              - name: MEMCACHED_HOST
                value: *props.memcachedAddr
