apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    name: gateway
spec:
  ports:
  - port: 80
    targetPort: web
    protocol: TCP
  selector:
    name: gateway
  type: LoadBalancer
