apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    name: memcached
spec:
  ports:
  - port: 11211
    targetPort: memcached
    protocol: TCP
  selector:
    name: memcached
  type: ClusterIP
